# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yincapp', '0002_auto_20170622_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FD', 'Food'), ('BK', 'Books'), ('GM', 'Games'), ('WH', 'Watches'), ('SW', 'Sportswear')], max_length=50),
        ),
    ]
